### ISSUE TITLE
划线为什么不能显示轨迹？

### ISSUE THREAD

**Issue by Suremotoo** [vipstone/drawingboard#1]
首先，我很喜欢这个项目，希望能做的更远更好。

1. **轨迹问题：** 除了第一个功能✏️铅笔划线和橡皮擦，其他的都没有划线的轨迹呢？还是说我的有问题？比如画个方形，鼠标直接拖，但是没有轨迹，只有鼠标放开的时候，图标才瞬间显示出来。
2. **扩展功能：** 能不能加上拖拽？方便画出来的可以修改，重新调整等。
3. **图标：** 图标最好换成高清的（1024*1024），我的是 mac ，显得是朦胧的感觉。

**Comment by vipstone** [comment]
你好，感谢留言，我来回答一下问题：
1.是这样子的，这个还算太完善，轨迹的问题很好实现，需要加2个鼠标事件就可以解决这个问题了。
2.拖拽是可以加的，但是加上控件编辑的功能之后，有点小瑕疵，新加图形的时候，很容易就误操作选中老固件了，这个在后期版本，可以加上。
3.mac还真没试过，标识下半年才有mac电脑，玩了会兼容一下mac上的样式。

谢谢你.

**Comment by Suremotoo** [comment]
mac 的分辨率比较高，retina 屏幕的更是舒服。我不懂前端，后期会做个小工具箱，想把这个项目给添加进去。
加油💪💪，我时刻关注。
