### ISSUE TITLE
图片下载问题

### ISSUE THREAD

**Issue by anncwb** [vipstone/drawingboard#2]
请问下,如果将网络图片放到canvas里面的话,保存的时候这张图片是保存不下来的,但是如果加载的是本地图片就可以了,这要怎么解决呢;.还有demo里面还是和您的git界面不一样,少了一些功能

**Comment by anncwb** [comment]
DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
网络图片保存的时候会报这个错

**Comment by vipstone** [comment]
设置crossOrigin: 'anonymous'，允许使用跨域的图片。
`
fabric.Image.fromURL('http://icdn.apigo.cn/paper.png?1', function (img) {

  canvas.add(img);

}, { crossOrigin: 'anonymous' });
` @anncwb

**Comment by anncwb** [comment]
谢谢
